### ISSUE TITLE
Why does the question always get set to completed?

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-inline-feedback#1]
It seems a bit odd that it always forces the question to completed after having scrolled to the feedback. What if you want to allow the user to have multiple attempts? Currently if you set `_attempts` to 2 or more the user can scroll up and select Submit and the question will reset but the Submit button doesn't reappear, you just get left with a greyed-out reset button.

**Comment by chris-steele** [comment]
@moloko This looks like an oversight. I've amended.
